# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
# We do not use maven-publish.yml as .m2/settings.xml is overridden in public repos. Instead, mvn deploy is
# called from local developer machine with user and key.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    #environment:
    #  name: Development

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create settings.xml
        uses: s4u/maven-settings-action@v2.8.0
        with:
          servers: |
            [
              {
                "id": "cats-api",
                "username": "${{ secrets.CATS_USERNAME }}",
                "password": "${{ secrets.CATS_PASSWORD }}"
              }
            ]

      - name: Build with Maven
        run: mvn -B package --file pom.xml
